### ISSUE TITLE
Authentication against a custom tenant in Pipes production gives a 401 error

### ISSUE THREAD

**Issue by MichaelBurgess** [turbot/steampipe-plugin-pipes#29]
**Describe the bug**
Authentication against a custom tenant in Pipes production gives a 401 error. Works for custom tenants in non-prod environments. E.g. acme.pipes.turbot-local.com works, but acme.pipes.turbot.com does. 

**Steampipe version (`steampipe -v`)**
Example: v0.23.0

**Plugin version (`steampipe plugin list`)**
Example:  v0.14.0

**To reproduce**
Create a user token for a custom production tenant and create a Pipes plugin connection for this host and for this token. Perform a query and you will get a 401.

**Expected behavior**
Authentication against the custom tenant should work like any other env / Pipes tenant.

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/steampipe-plugin-pipes/pull/30
